// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "_developer/api.mdx": () => import("../content/docs/_developer/api.mdx?collection=docs"), "_developer/cli.mdx": () => import("../content/docs/_developer/cli.mdx?collection=docs"), "_developer/webhooks.mdx": () => import("../content/docs/_developer/webhooks.mdx?collection=docs"), "domains/auth-codes.mdx": () => import("../content/docs/domains/auth-codes.mdx?collection=docs"), "domains/nameservers-dns.mdx": () => import("../content/docs/domains/nameservers-dns.mdx?collection=docs"), "domains/registering-domains.mdx": () => import("../content/docs/domains/registering-domains.mdx?collection=docs"), "domains/transferring-domains.mdx": () => import("../content/docs/domains/transferring-domains.mdx?collection=docs"), "getting-started/creating-account.mdx": () => import("../content/docs/getting-started/creating-account.mdx?collection=docs"), "getting-started/dashboard-overview.mdx": () => import("../content/docs/getting-started/dashboard-overview.mdx?collection=docs"), "getting-started/email-verification.mdx": () => import("../content/docs/getting-started/email-verification.mdx?collection=docs"), "billing/invoices.mdx": () => import("../content/docs/billing/invoices.mdx?collection=docs"), "billing/payment-methods.mdx": () => import("../content/docs/billing/payment-methods.mdx?collection=docs"), "billing/plan-upgrades.mdx": () => import("../content/docs/billing/plan-upgrades.mdx?collection=docs"), "hosting/cpanel-access.mdx": () => import("../content/docs/hosting/cpanel-access.mdx?collection=docs"), "hosting/databases.mdx": () => import("../content/docs/hosting/databases.mdx?collection=docs"), "hosting/email-accounts.mdx": () => import("../content/docs/hosting/email-accounts.mdx?collection=docs"), "hosting/php-versions.mdx": () => import("../content/docs/hosting/php-versions.mdx?collection=docs"), "hosting/wordpress-install.mdx": () => import("../content/docs/hosting/wordpress-install.mdx?collection=docs"), "ssl/automated-ssl.mdx": () => import("../content/docs/ssl/automated-ssl.mdx?collection=docs"), "ssl/https-redirection.mdx": () => import("../content/docs/ssl/https-redirection.mdx?collection=docs"), "ssl/troubleshooting.mdx": () => import("../content/docs/ssl/troubleshooting.mdx?collection=docs"), }),
};
export default browserCollections;